table:
  name: consumer_application
  schema: public
object_relationships:
  - name: new_consumer
    using:
      foreign_key_constraint_on: consumer_id
array_relationships:
  - name: consumer_application_states
    using:
      foreign_key_constraint_on:
        column: consumer_application_id
        table:
          name: consumer_application_state
          schema: public
