import { EGovernorate } from '@common/enums/address.enums';
import { EBankName } from '@common/enums/bank.enums';
import { ECategory, EEmployeeRole, EStorePhoneType } from '@common/enums/partner.enums';
import { sortLabelsFn } from '@common/helpers/array.helpers';

export const activityOptions: { value: ECategory; label: string }[] = [
  { value: ECategory.Accessories, label: 'إكسسوارات' },
  { value: ECategory.AutoSpareParts, label: 'قطع غيار السيارات / خدمة السيارات' },
  { value: ECategory.Education, label: 'تعليم' },
  { value: ECategory.Electronics, label: 'أجهزة منزلية' },
  { value: ECategory.Fashion, label: 'ملابس' },
  { value: ECategory.Finishing, label: 'تشطيبات' },
  { value: ECategory.Furniture, label: 'أثاث منزلي' },
  { value: ECategory.HomeWare, label: 'أدوت منزلية' },
  { value: ECategory.Medical, label: 'خدمات طبية' },
  { value: ECategory.Optics, label: 'بصريات' },
  { value: ECategory.Sports, label: 'رياضة' },
  { value: ECategory.TourismAndEntertainment, label: 'سياحة و ترفيه' },
  { value: ECategory.WeddingHalls, label: 'قاعات أفراح' },
  { value: ECategory.Mobile, label: 'موبايلات والكترونيات' },
  { value: ECategory.ShoppingHubs, label: 'مراكز تسوق' },
  { value: ECategory.Motorcycles, label: 'موتوسيكلات' },
].sort(sortLabelsFn);

export const governorateOptions = [
  {
    value: EGovernorate.Assiut,
    label: 'Assiut',
    cities: [
      { value: 'البيسرى', label: 'البيسرى' },
      { value: 'الحقوقيين', label: 'الحقوقيين' },
      { value: 'الحمراء', label: 'الحمراء' },
      { value: 'المجاهدين', label: 'المجاهدين' },
      { value: 'الوليديه', label: 'الوليديه' },
      { value: 'حى السادات', label: 'حى السادات' },
      { value: 'ساحل سليم', label: 'ساحل سليم' },
      { value: 'شركة فريال', label: 'شركة فريال' },
      { value: 'شركة قلته', label: 'شركة قلته' },
      { value: 'شركة كدوانى', label: 'شركة كدوانى' },
      { value: 'غرب البلد', label: 'غرب البلد' },
      { value: 'مدينه المعلمين', label: 'مدينه المعلمين' },
      { value: 'مدينه مبارك', label: 'مدينه مبارك' },
      { value: 'مركز ابنوب', label: 'مركز ابنوب' },
      { value: 'مركز ابو تيج', label: 'مركز ابو تيج' },
      { value: 'مركز اسيوط', label: 'مركز اسيوط' },
      { value: 'مركز الغنايم', label: 'مركز الغنايم' },
      { value: 'مركز الفتح', label: 'مركز الفتح' },
      { value: 'مركز ديروط', label: 'مركز ديروط' },
      { value: 'مركز صدفا', label: 'مركز صدفا' },
      { value: 'مركز منفلوط', label: 'مركز منفلوط' },
      { value: 'مركز البدارى', label: 'مركز البدارى' },
      { value: 'مصنع سيد', label: 'مصنع سيد' },
      { value: 'نائلة خاتون', label: 'نائلة خاتون' },
      { value: 'نزلة عبداللاه', label: 'نزلة عبداللاه' },
      { value: 'ديروت', label: 'ديروت' },
      { value: 'مركز القوصيه', label: 'مركز القوصيه' },
      { value: 'درنكة', label: 'درنكة' },
      { value: 'منقباد', label: 'منقباد' },
      { value: 'جزيره الوسطى القبليه', label: 'جزيره الوسطى القبليه' },
    ].sort(sortLabelsFn),
  },
  {
    value: EGovernorate.SOHAG,
    label: 'SOHAG',
    cities: [
      { value: 'أخميم', label: 'أخميم' },
      { value: 'البلينا', label: 'البلينا' },
      { value: 'العسيرات', label: 'العسيرات' },
      { value: 'الكوثر', label: 'الكوثر' },
      { value: 'المراغة', label: 'المراغة' },
      { value: 'المنشاه', label: 'المنشاه' },
      { value: 'جرجا', label: 'جرجا' },
      { value: 'جزيره شندويل', label: 'جزيره شندويل' },
      { value: 'جهينة', label: 'جهينة' },
      { value: 'ساقلته', label: 'ساقلته' },
      { value: 'سوهاج', label: 'سوهاج' },
      { value: 'طما', label: 'طما' },
      { value: 'طهطا', label: 'طهطا' },
      { value: 'برديس', label: 'برديس' },
      { value: 'دار السلام', label: 'دار السلام' },
      { value: 'القرامطه غرب وشرق', label: 'القرامطه غرب وشرق' },
    ],
  },
  {
    value: EGovernorate.Qena,
    label: 'Qena',
    cities: [
      { value: 'اشراف', label: 'اشراف' },
      { value: 'ابو تشت', label: 'ابو تشت' },
      { value: 'الجبلاو', label: 'الجبلاو' },
      { value: 'الدير', label: 'الدير' },
      { value: 'الوقف', label: 'الوقف' },
      { value: 'دشنا', label: 'دشنا' },
      { value: 'دندرة', label: 'دندرة' },
      { value: 'فرشوت', label: 'فرشوت' },
      { value: 'قفط', label: 'قفط' },
      { value: 'قنا', label: 'قنا' },
      { value: 'قوص', label: 'قوص' },
      { value: 'نجع حمادى', label: 'نجع حمادى' },
      { value: 'نقاده', label: 'نقاده' },
      { value: 'بركة', label: 'بركة' },
      { value: 'المحروسة', label: 'المحروسة' },
      { value: 'الترامسة', label: 'الترامسة' },
      { value: 'الالمونيوم', label: 'الالمونيوم' },
      { value: 'نجع عزوز', label: 'نجع عزوز' },
      { value: 'عزبه الألفى', label: 'عزبه الألفى' },
    ],
  },
].sort(sortLabelsFn);

export const bankOptions: { value: EBankName; label: string }[] = [
  { value: EBankName.AAIB, label: 'البنك العربي الأفريقي الدولي' },
  { value: EBankName.ABC, label: 'المؤسسة العربية المصرفية' },
  { value: EBankName.ABK, label: 'البنك الأهلي الكويتي - مصر' },
  { value: EBankName.ADCB, label: 'بنك أبوظبي التجاري - مصر' },
  { value: EBankName.ADIB, label: 'مصرف أبوظبي الإسلامي - مصر' },
  { value: EBankName.PDAC, label: 'البنك الزراعي المصري' },
  { value: EBankName.AI, label: 'البنك العربي للاستثمار والتجارة الخارجية' },
  { value: EBankName.BOA, label: 'بنك الإسكندرية' },
  { value: EBankName.ARAB, label: 'البنك العربي' },
  { value: EBankName.AUB, label: 'البنك الأهلي المتحد - مصر' },
  { value: EBankName.BDC, label: 'بنك القاهرة' },
  { value: EBankName.AIB, label: 'بنك الاستثمار العربي' },
  { value: EBankName.MISR, label: 'بنك مصر' },
  { value: EBankName.CAE, label: 'بنك كريدي أجريكول - مصر' },
  { value: EBankName.CIB, label: 'البنك التجاري الدولي' },
  { value: EBankName.EALB, label: 'البنك المصري لتنمية الصادرات' },
  { value: EBankName.EBE, label: 'بنك تنمية الصادرات' },
  { value: EBankName.FAB, label: 'بنك أبوظبي الأول - مصر' },
  { value: EBankName.FAIB, label: 'بنك فيصل الإسلامي' },
  { value: EBankName.HDB, label: 'بنك التعمير والإسكان' },
  { value: EBankName.HSBC, label: 'بنك إتش إس بي سي - مصر' },
  { value: EBankName.IDB, label: 'بنك التنمية الصناعية' },
  { value: EBankName.MASH, label: 'بنك المشرق - مصر' },
  { value: EBankName.MIDB, label: 'ميد بنك' },
  { value: EBankName.ENBD, label: 'بنك الإمارات دبي الوطني - مصر' },
  { value: EBankName.NBE, label: 'البنك الأهلي المصري' },
  { value: EBankName.NBK, label: 'بنك الكويت الوطني - مصر' },
  { value: EBankName.QNB, label: 'بنك قطر الوطني الأهلي' },
  { value: EBankName.SAIB, label: 'بنك الشركة المصرفية العربية الدولية' },
  { value: EBankName.SC, label: 'البنك الأهلي سوسيتيه جنرال - مصر' },
  { value: EBankName.SCB, label: 'بنك ستاندرد تشارترد - مصر' },
  { value: EBankName.UB, label: 'المصرف المتحد' },
  { value: EBankName.BBE, label: 'بنك التجاري وفا - مصر' },
  { value: EBankName.ARIB, label: 'المصرف العربى الدولى' },
  { value: EBankName.EGB, label: 'البنك المصري الخليجي' },
  { value: EBankName.ABRK, label: 'بنك البركة - مصر' },
  { value: EBankName.NBG, label: 'البنك الأهلي اليوناني' },
  { value: EBankName.NSB, label: 'بنك ناصر الاجتماعي' },
  { value: EBankName.POST, label: 'البريد المصري' },
].sort(sortLabelsFn).map((bank => ({...bank, label: `${bank.label} - ${bank.value}`})));

export const phoneTypeOptions = [
  { value: EStorePhoneType.Contactable, label: 'Contactable' },
  { value: EStorePhoneType.Hotline, label: 'Hotline' },
  { value: EStorePhoneType.Whatsapp, label: 'Whatsapp' },
].sort(sortLabelsFn);

export const employeeRoles = [
  { value: EEmployeeRole.Assistant, label: 'Assistant' },
  { value: EEmployeeRole.Cashier, label: 'Cashier' },
  { value: EEmployeeRole.Finance, label: 'Finance' },
  { value: EEmployeeRole.Manager, label: 'Manager' },
  { value: EEmployeeRole.StoreAdmin, label: 'Store Admin' },
].sort(sortLabelsFn);

export const tenorOptions = [
  {
    value: '6_months',
    label: '6 Months',
  },
  {
    value: '12_months',
    label: '12 Months',
  },
  {
    value: '18_months',
    label: '18 Months',
  },
  {
    value: '24_months',
    label: '24 Months',
  },
  {
    value: '36_months',
    label: '36 Months',
  },
  {
    value: '48_months',
    label: '48 Months',
  },
];
