// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: scoring_service.proto

package minicash_scoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Validate that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Validate that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for GetCreditLimit
type GetCreditLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MobileNumber string `protobuf:"bytes,1,opt,name=mobileNumber,proto3" json:"mobileNumber,omitempty"`
}

func (x *GetCreditLimitRequest) Reset() {
	*x = GetCreditLimitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoring_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCreditLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditLimitRequest) ProtoMessage() {}

func (x *GetCreditLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scoring_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditLimitRequest.ProtoReflect.Descriptor instead.
func (*GetCreditLimitRequest) Descriptor() ([]byte, []int) {
	return file_scoring_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCreditLimitRequest) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

// Response for GetCreditLimit
type GetCreditLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserExists  bool  `protobuf:"varint,1,opt,name=user_exists,json=userExists,proto3" json:"user_exists,omitempty"`
	CreditLimit int32 `protobuf:"varint,2,opt,name=credit_limit,json=creditLimit,proto3" json:"credit_limit,omitempty"`
}

func (x *GetCreditLimitResponse) Reset() {
	*x = GetCreditLimitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoring_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCreditLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditLimitResponse) ProtoMessage() {}

func (x *GetCreditLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scoring_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditLimitResponse.ProtoReflect.Descriptor instead.
func (*GetCreditLimitResponse) Descriptor() ([]byte, []int) {
	return file_scoring_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCreditLimitResponse) GetUserExists() bool {
	if x != nil {
		return x.UserExists
	}
	return false
}

func (x *GetCreditLimitResponse) GetCreditLimit() int32 {
	if x != nil {
		return x.CreditLimit
	}
	return 0
}

var File_scoring_service_proto protoreflect.FileDescriptor

var file_scoring_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67,
	0x22, 0x3b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x5c, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x75, 0x73,
	0x65, 0x72, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0x63, 0x0a, 0x0e, 0x53,
	0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1e, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x16, 0x5a, 0x14, 0x70, 0x62, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x63, 0x61, 0x73, 0x68, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scoring_service_proto_rawDescOnce sync.Once
	file_scoring_service_proto_rawDescData = file_scoring_service_proto_rawDesc
)

func file_scoring_service_proto_rawDescGZIP() []byte {
	file_scoring_service_proto_rawDescOnce.Do(func() {
		file_scoring_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_scoring_service_proto_rawDescData)
	})
	return file_scoring_service_proto_rawDescData
}

var file_scoring_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scoring_service_proto_goTypes = []interface{}{
	(*GetCreditLimitRequest)(nil),  // 0: scoring.GetCreditLimitRequest
	(*GetCreditLimitResponse)(nil), // 1: scoring.GetCreditLimitResponse
}
var file_scoring_service_proto_depIdxs = []int32{
	0, // 0: scoring.ScoringService.GetCreditLimit:input_type -> scoring.GetCreditLimitRequest
	1, // 1: scoring.ScoringService.GetCreditLimit:output_type -> scoring.GetCreditLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scoring_service_proto_init() }
func file_scoring_service_proto_init() {
	if File_scoring_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scoring_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCreditLimitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoring_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCreditLimitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scoring_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scoring_service_proto_goTypes,
		DependencyIndexes: file_scoring_service_proto_depIdxs,
		MessageInfos:      file_scoring_service_proto_msgTypes,
	}.Build()
	File_scoring_service_proto = out.File
	file_scoring_service_proto_rawDesc = nil
	file_scoring_service_proto_goTypes = nil
	file_scoring_service_proto_depIdxs = nil
}
