repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: "(alembic)"

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
    description: This hook sorts imports in the files.
    args: ["--profile", "black"]
    exclude: "(alembic)"


- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    name: black
    description: This hook runs black formatter and fixes most PEP8 formatting issues automatically.
    exclude: "(alembic)"


-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Flake8 (Code Linting)
        stages: [commit]
        args: [--max-complexity=10, --max-line-length=120]
        exclude: "(alembic|migrations|docs|.venv|dist|build|__pycache__|.git|docker)/.*"

-   repo: local
    hooks:
      - id: pytest
        name: Pytest (Unit Testing)
        language: system
        entry: docker compose -f docker/docker-compose.yml run --rm fastapi-template python -m pytest -v -s --cov --cov-fail-under=100
        always_run: true
        pass_filenames: false
        stages: [commit]
