default_stages: [commit]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
        stages: [commit]
      - id: check-case-conflict
      - id: name-tests-test
      - id: check-json
      - id: check-yaml
        exclude: ^deployment/
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "(static|deployment)/.*"
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Flake8 (Code Linting)
        stages: [commit]
        exclude: "(migrations|alembic|docs|venv|dist|build|__pycache__|.git)/.*"

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^static/
        language: python
        types: [python]
        args: ["--line-length=120"]

  - repo: local
    hooks:
      - id: pytest
        name: Pytest (Unit Testing)
        language: python
        entry: venv/bin/python -m pytest -v -s --cache-clear  --cov --cov-fail-under=99 --cov-report term-missing
        always_run: true
        pass_filenames: false
        stages: [commit]
