FROM node:20-bullseye

# Install Chromium
RUN apt-get update && apt-get install -y chromium

WORKDIR /app
COPY package*.json ./
RUN npm i
COPY . . 
EXPOSE 3000
ENV NODE_PATH /app/node_modules/
CMD [ "npm", "run", "dev" ]