export type ScoringDto = {
  ssn: string;
  workType: string;
  city: string;
  burden: string;
  district: string;
  governorate: string;
  salary: number;
  additionalSalary: number;
  address: string;
  addressDescription: string;
  jobName: string;
  houseType: string;
  guarantorJob: string;
  guarantorRelationship: string;
  company: string;
  car: number;
  club: string;
  maritalStatus: string;
  stateName: string;
  mobileNumber: string;
  name: string;
};
