server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: risk-engine
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        regex: "/risk-engine.*"
        action: keep
      - source_labels: [ __meta_docker_container_log_path ]
        target_label: __path__
        action: replace
        regex: "/var/lib/docker/containers/(.*)\\..*"
        replacement: "/var/lib/docker/containers/\\1.log"
      - source_labels: [ __meta_docker_container_id ]
        target_label: container_id
        action: replace
      - source_labels: [ __meta_docker_container_name ]
        target_label: container_name
        action: replace
      - source_labels: [ __meta_docker_container_image ]
        target_label: container_image
        action: replace
      - source_labels: [ __meta_docker_container_network_mode ]
        target_label: network_mode
        action: replace
      - source_labels: [ __meta_docker_container_network_mode ]
        target_label: job
        action: replace
        replacement: risk-engine

    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - match:
          selector: '{level!=""}'
          stages:
            - json:
                expressions:
                  ts: ts
                  level: level
                  msg: msg
            - labels:
                level:
                msg:
