log:
  level: debug
  leak_sensitive_values: true
  format: json

urls:
  login: http://localhost:4455/login
  consent: http://localhost:4455/consent
  self:
    issuer: http://localhost:4455
    public: http://localhost:4455

oauth2:
  client_credentials:
    default_grant_allowed_scope: true

secrets:
  system:
    - 9b74c9897bac770ffc029102a200c5dee3afed0047b08059d0fada10f400c1e5
