services:

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.3
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: [-config.file=/etc/promtail/promtail.yaml]
    depends_on:
      - loki
    networks:
      - mylo

  loki:
    container_name: loki
    image: grafana/loki:2.9.3
    volumes:
      - ./config/loki/loki.yaml:/etc/loki.yaml
    command: ['-config.file=/etc/loki.yaml']
    ports:
      - '3100:3100'
    networks:
      - mylo

  tempo:
    container_name: tempo
    image: grafana/tempo:2.3.1
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - '3200:3200' ## http client port
      - '9095:9095' ## grpc client port
      - '9096:9096' ## reciever http port
      - '9098:9098' ## reciever grpc port
    networks:
      - mylo

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=debug
    volumes:
      - promdata:/prometheus/data
      - ./config/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - mylo

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.92.0
    command:
      - '--config'
      - '/etc/otel-collector.yaml'
    volumes:
      - ./config/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '4318:4318' ## reciever http port
      - '4317:4317' ## receiver grpc port
    networks:
      - mylo

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    volumes:
      - type: bind
        source: ./config/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: ./config/grafana/dashboards
        target: /var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_URL=postgres://postgres:admin@postgres:5432/grafana
    ports:
      - '4000:3000'
    networks:
      - mylo

volumes:
  promdata: