global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: "lms-server"
    scrape_interval: 10s
    static_configs:
      - targets:
        - "host.docker.internal:2223"
        labels:
          deployment_environment: prod
  - job_name: "lms-worker"
    scrape_interval: 10s
    static_configs:
      - targets:
        - "host.docker.internal:2224"
        - "host.docker.internal:2225"
        labels:
          deployment_environment: prod

