apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: tempo


  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET


  - name: PostgresMyloDB
    type: postgres
    url: postgres:5432
    database: mylo
    user: postgres
    secureJsonData:
      password: "admin"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    uid: myloprod


  - name: PostgresMyloLMSDB
    type: postgres
    url: postgres:5432
    database: lms
    user: postgres
    secureJsonData:
      password: "admin"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
    uid: mylolmsprod