
export enum ConsumerStatus {
    AWAITING_ACTIVATION = 'AWAITING_ACTIVATION',
    ACTIVE = 'ACTIVE',
    BLOCKED = 'BLOCKED',
    WAITING_LIST = 'WAITING_LIST',
    REJECTED = 'REJECTED',
    DEACTIVATED = 'DEACTIVATED'

}