// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/loans/consumer/{consumer_id}": {
            "get": {
                "description": "Get all loans for a consumer by consumer ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all loans for a user",
                "operationId": "get-all-loans-for-consumer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumer ID",
                        "name": "consumerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/domain.GetAllLoansForConsumerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.LmsHttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.LmsHttpError"
                        }
                    }
                }
            }
        },
        "/api/loans/merchant/{merchant_id}": {
            "get": {
                "description": "Get all loans for a merchant by merchant ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all loans for a user",
                "operationId": "get-all-loans-for-merchant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Merchant ID",
                        "name": "merchantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/domain.GetAllLoansForMerchantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/domain.LmsHttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.LmsHttpError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "get request to check service health",
                "produces": [
                    "application/json"
                ],
                "summary": "get request to check service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.HealthResponse"
                        }
                    },
                    "408": {
                        "description": "fail",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "fail",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.GetAllLoansForConsumerResponse": {
            "type": "object",
            "properties": {
                "loans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.Loan"
                    }
                }
            }
        },
        "domain.GetAllLoansForMerchantResponse": {
            "type": "object",
            "properties": {
                "loans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.MerchantLoan"
                    }
                }
            }
        },
        "domain.LmsHttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "domain.Money": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                }
            }
        },
        "github_com_btechlabs_lms-lite_internal_http_domain.Loan": {
            "type": "object",
            "properties": {
                "admin_fee": {
                    "$ref": "#/definitions/domain.Money"
                },
                "booked_at": {
                    "type": "string"
                },
                "commercial_offer_id": {
                    "type": "string"
                },
                "consumer_id": {
                    "type": "string"
                },
                "correlation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_status": {
                    "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.LoanStatus"
                },
                "financial_product_key": {
                    "type": "string"
                },
                "financial_product_version": {
                    "type": "string"
                },
                "loan_id": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "string"
                },
                "payment_schedule": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.LoanPaymentSchedule"
                    }
                },
                "statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.LoanStatus"
                    }
                }
            }
        },
        "github_com_btechlabs_lms-lite_internal_http_domain.LoanPaymentSchedule": {
            "type": "object",
            "properties": {
                "due_date": {
                    "type": "string"
                },
                "grace_period_end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "interest_due": {
                    "$ref": "#/definitions/domain.Money"
                },
                "late_fee_due": {
                    "$ref": "#/definitions/domain.Money"
                },
                "loan_balance": {
                    "$ref": "#/definitions/domain.Money"
                },
                "loan_id": {
                    "type": "string"
                },
                "paid_date": {
                    "type": "string"
                },
                "paid_interest": {
                    "$ref": "#/definitions/domain.Money"
                },
                "paid_late_fee": {
                    "$ref": "#/definitions/domain.Money"
                },
                "paid_principal": {
                    "$ref": "#/definitions/domain.Money"
                },
                "principal_due": {
                    "$ref": "#/definitions/domain.Money"
                }
            }
        },
        "github_com_btechlabs_lms-lite_internal_http_domain.LoanStatus": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "status_type": {
                    "type": "string"
                }
            }
        },
        "github_com_btechlabs_lms-lite_internal_http_domain.MerchantLoan": {
            "type": "object",
            "properties": {
                "admin_fee": {
                    "$ref": "#/definitions/domain.Money"
                },
                "booked_at": {
                    "type": "string"
                },
                "commercial_offer_id": {
                    "type": "string"
                },
                "consumer_id": {
                    "type": "string"
                },
                "correlation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_status": {
                    "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.LoanStatus"
                },
                "financial_product_key": {
                    "type": "string"
                },
                "financial_product_version": {
                    "type": "string"
                },
                "loan_id": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "statuses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_btechlabs_lms-lite_internal_http_domain.LoanStatus"
                    }
                },
                "transaction_id": {
                    "type": "string"
                },
                "transaction_status": {
                    "type": "string"
                }
            }
        },
        "rest.HealthResponse": {
            "type": "object",
            "properties": {
                "conductor_alive": {
                    "type": "boolean"
                },
                "database_alive": {
                    "type": "boolean"
                },
                "is_alive": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
