{
 "title": "Conductor and Workflows",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Workflow Latencies (Name and Percentile)",
   "type": "timeseries",
   "description": "Timer indicating the time taken for completing the workflows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "workflow_completed_seconds{application=\"ConductorServer\", quantile=\"0.95\"}",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflows currently running",
   "type": "timeseries",
   "description": "Gauge for the number of running workflows.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "workflow_running{application=\"ConductorServer\"}",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflow failures/sec",
   "type": "timeseries",
   "description": "Counter indicating the number of workflows failed per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "workflow_completed_seconds_count{application=\"ConductorServer\", status!~\"COMPLETED|SCHEDULED|IN_PROGRESS\"}",
     "legendFormat": "{{workflowName}} - {{status}}"
    }
   ]
  },
  {
   "title": "Workflow completion/sec",
   "type": "timeseries",
   "description": "Counter indicating the number of workflows completed per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "workflow_completed_seconds_count{application=\"ConductorServer\", status=~\"COMPLETED\"}",
     "legendFormat": "{{workflowName}} - {{status}}"
    }
   ]
  },
  {
   "title": "Task Completed / sec",
   "type": "timeseries",
   "description": "Counter for no. of tasks completed successfully per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "task_completed_seconds_count{application=\"ConductorServer\", status=~\"COMPLETED\"}",
     "legendFormat": "{{taskType}}"
    }
   ]
  }
 ]
}