{
 "title": "LMS Runtime Metrics",
 "description": "Process status and runtime metrics published by Go Prometheus client.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(target_info{service_name=\"lms-server\"}[$__range]) / ($__range_s / 10)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Request Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{job=\"lms-server\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{job=\"lms-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_sum{job=\"lms-server\"} / http_server_duration_milliseconds_count{job=\"lms-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(http_server_duration_milliseconds_count{job=\"lms-server\", http_status_code=~\"2.*\"}[$__range])) / sum(sum_over_time(http_server_duration_milliseconds_count{job=\"lms-server\"}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 5xx requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(http_server_duration_milliseconds_count{job=\"lms-server\", http_status_code=~\"5.*\"}[$__range])) / sum(sum_over_time(http_server_duration_milliseconds_count{job=\"lms-server\"}[$__range]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum_over_time(target_info{service_name=\"lms-worker\"}[$__range]) / ($__range_s / 10)) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(http_server_duration_milliseconds_sum{job=\"lms-server\"}[$__range]) / sum_over_time(http_server_duration_milliseconds_count{job=\"lms-server\"}[$__range]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_duration_milliseconds_bucket{job=\"lms-server\", http_status_code=~\"2.*\"}[$__range])) by (le))",
     "legendFormat": "99 Percentile"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_duration_milliseconds_bucket{job=\"lms-server\", http_status_code=~\"2.*\"}[$__range])) by (le))",
     "legendFormat": "95 Percentile"
    },
    {
     "expr": "histogram_quantile(.75,sum(rate(http_server_duration_milliseconds_bucket{job=\"lms-server\", http_status_code=~\"2.*\"}[$__range])) by (le))",
     "legendFormat": "75 Percentile"
    }
   ]
  },
  {
   "title": "GoRuntime Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goroutines - Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"lms-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines - Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"lms-worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"lms-server\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "OS Threads - Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_threads{job=\"lms-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Threads - Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"lms-worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Server",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"lms-server\"}",
     "legendFormat": "Stack In-Use"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"lms-server\"}",
     "legendFormat": "Heap In-Use"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"lms-server\"}",
     "legendFormat": "Allocated Bytes"
    }
   ]
  }
 ]
}