with-expecter: True
inpackage: True
#dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
all: True
packages:
  github.com/btechlabs/lms-lite:
    config:
      recursive: True
      exclude:
        - pkg
        - swagger
        - vendor