FROM golang:1.22.3-alpine3.19

USER root
RUN apk update && apk add --no-cache g++ make openssh-client bash git curl

# Install reflex for hot reloading by building from source
RUN go install github.com/cespare/reflex@latest

WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Copy the rest of the application code
COPY . .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Create necessary directories
RUN mkdir -p /etc/config/lms-lite

# Copy assets
COPY assets /etc/config/lms-lite

# Expose the application port
EXPOSE 9090

# Command to run the application with reflex for hot reloading
CMD ["reflex", "-c", "reflex-worker.conf"]