name: Slack Notifications

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    environment: 'Android'
    steps:
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C0859N0R5EX\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Repository*: ${{ github.event.repository.name }}\n*Opened By:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

